// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: model/message.proto

package model

import (
	context "context"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CommandSender_SendCommand_FullMethodName = "/model.CommandSender/SendCommand"
	CommandSender_GetStatus_FullMethodName   = "/model.CommandSender/GetStatus"
)

// CommandSenderClient is the client API for CommandSender service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CommandSenderClient interface {
	SendCommand(ctx context.Context, in *Command, opts ...grpc.CallOption) (*empty.Empty, error)
	GetStatus(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Status, error)
}

type commandSenderClient struct {
	cc grpc.ClientConnInterface
}

func NewCommandSenderClient(cc grpc.ClientConnInterface) CommandSenderClient {
	return &commandSenderClient{cc}
}

func (c *commandSenderClient) SendCommand(ctx context.Context, in *Command, opts ...grpc.CallOption) (*empty.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, CommandSender_SendCommand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commandSenderClient) GetStatus(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Status, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Status)
	err := c.cc.Invoke(ctx, CommandSender_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CommandSenderServer is the server API for CommandSender service.
// All implementations must embed UnimplementedCommandSenderServer
// for forward compatibility.
type CommandSenderServer interface {
	SendCommand(context.Context, *Command) (*empty.Empty, error)
	GetStatus(context.Context, *empty.Empty) (*Status, error)
	mustEmbedUnimplementedCommandSenderServer()
}

// UnimplementedCommandSenderServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCommandSenderServer struct{}

func (UnimplementedCommandSenderServer) SendCommand(context.Context, *Command) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendCommand not implemented")
}
func (UnimplementedCommandSenderServer) GetStatus(context.Context, *empty.Empty) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedCommandSenderServer) mustEmbedUnimplementedCommandSenderServer() {}
func (UnimplementedCommandSenderServer) testEmbeddedByValue()                       {}

// UnsafeCommandSenderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CommandSenderServer will
// result in compilation errors.
type UnsafeCommandSenderServer interface {
	mustEmbedUnimplementedCommandSenderServer()
}

func RegisterCommandSenderServer(s grpc.ServiceRegistrar, srv CommandSenderServer) {
	// If the following call pancis, it indicates UnimplementedCommandSenderServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CommandSender_ServiceDesc, srv)
}

func _CommandSender_SendCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Command)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommandSenderServer).SendCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommandSender_SendCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommandSenderServer).SendCommand(ctx, req.(*Command))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommandSender_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommandSenderServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommandSender_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommandSenderServer).GetStatus(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// CommandSender_ServiceDesc is the grpc.ServiceDesc for CommandSender service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CommandSender_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "model.CommandSender",
	HandlerType: (*CommandSenderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendCommand",
			Handler:    _CommandSender_SendCommand_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _CommandSender_GetStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "model/message.proto",
}
